### ISSUE TITLE
Spawn distance of OPFOR air forces relative to mission area & balance of air units

### ISSUE THREAD

**Issue by Quebeczulu** [Brig13Team/Operation_Kerberos#106]
Problemschilderung:
1. Opfor Lufteinheiten sind im Vergleich zu eigenen Luftkräften sehr stark. AA missles treffen eigentlich kaum (oft von 4 missles kein einziger Treffer), PARS gehen besser (ist aber doch eigentlich nicht Sinn der Sache). Trefferwirkung ist selbst im Trefferfall minimal.
2. Gegnerische Lufteinheiten zerstören mit der ersten Rakete zu 80-90% die eigene EInheit. Ein Ausweichen ist auf Grund der kurzen bis nicht vorhandenen Reaktionszeit infolge sehr kurzer Spawndistanzen nicht möglich. Flares wirken nicht.

Lösungsvorschlag:
ad 1: Waffenwirkungen überprüfen
ad 2: deutlich größere Spawndistanzen.

Stehe für Rückfragen gerne zur Verfügung.
Quebec

**Comment by Dorbedo** [comment]
changed
