### ISSUE TITLE
Advanced AA

### ISSUE THREAD

**Issue by iJesuz** [Brig13Team/Operation_Kerberos#108]
- [ ] ZSU won't fire ground target
- [ ] ZSU radar to detect air vehicles around 1500 meter
- [ ] ZSU communication between ZSU's and Radars

**Comment by iJesuz** [comment]
Our current radar has a problem: Low flying helicopters are detected. Only the distance matters. We should think about adding an intersect check to reward low flying helicopters in valleys.

**Comment by iJesuz** [comment]
Change the spawned conter jet depending the detected air vehicle.

**Comment by Dorbedo** [comment]
Long time ago, there was a line intersection check. Looks like it got missing during some changes.

**Comment by Dorbedo** [comment]
Done in ada784e0d4b91539c1ef2b3c29bb50381732f247
