### ISSUE TITLE
Sidemissions

### ISSUE THREAD

**Issue by Dorbedo** [Brig13Team/Operation_Kerberos#16]
Sidemissionlist:

- [x] Sidemission handling #30 

- [ ] minefield: #24 
- [x] deserters: #25 
- [x] crashed aircrafts #26 
- [x] crashed sdv #27 
- [x] civilian supplies #28 
- [ ] enemy chopper #29 

- [x] conter part #32

**Comment by iJesuz** [comment]
i'm currently working on:
* deserters
  * random spawned features
  * intel number and precision depends on how well the players respected the random feature
* crashed aircrafts
  * blufor and opfor aircrafts
  * intel depends on side
  * intel has to be taken to base
* crashed sdvs
  * underwater combat
  * intel has to be taken to base
* civilian supplies
  * maybe civs get angry if it takes to long

when i finished this i will start working on other ideas (see ideas above)

**Comment by Dorbedo** [comment]
creation of marine-missions now as side-missions

**Comment by Dorbedo** [comment]
created issues for each mission

**Comment by Dorbedo** [comment]
Sidemissions for V0.15 done -> enhancement pushed into next milestone

**Comment by Dorbedo** [comment]
combined in #100
