### ISSUE TITLE
[Bug] No Ambient Sounds

### ISSUE THREAD

**Issue by blackvenom2** [Brig13Team/Operation_Kerberos#230]
Operation Kerberos has no Ambient Sounds. No Wind, No Rain, etc. (Rain only near vehicles)

**Comment by Dorbedo** [comment]
Not a bug, a feature.
https://github.com/Brig13Team/Operation_Kerberos/blob/master/missions/Operation_Kerberos.Altis/main/XEH_postInit.sqf#L11
Will be changed.
