### ISSUE TITLE
Mission discription not clear

### ISSUE THREAD

**Issue by HuTcHGER** [Brig13Team/Operation_Kerberos#233]
https://github.com/Brig13Team/Operation_Kerberos/blob/aab09064225e711c23775e6d112c14b53e4cf0c0/missions/Operation_Kerberos.Altis/stringtable.xml#L236

Differences between german and english discription of mission. Unclear if one or more comander should been arrested. In german translation you should take more , in english you need only one !

**Comment by Dorbedo** [comment]
There can be 1,2 or 3 commanders.
So it's a small typo inside the header.

**Comment by HuTcHGER** [comment]
Thx for fast response , but check pls also the **discripton** of mission not only the header

**Comment by HuTcHGER** [comment]
May be better translation from german into english:

**Capture the hostile commanders of the region. Return them back into base for interrogation**

**Comment by Dorbedo** [comment]
Feel free to provide a pull request.
