### ISSUE TITLE
tweak crate spawner

### ISSUE THREAD

**Issue by blackvenom2** [Brig13Team/Operation_Kerberos#286]
sync crate spawner with arsenal

//items that are on arsenal blacklisted are currently still available via crate spawner

**Comment by Dorbedo** [comment]
It is already synced.

**Comment by blackvenom2** [comment]
vg-40sz and some other grenades for rhs aks are available in spawner but not in arsenal.

**Comment by blackvenom2** [comment]
e.g. even russian gl-flares(vg-op40p) are missing in arsenal but available in crate spawn

**Comment by Dorbedo** [comment]
Not reproducable.

The cratespawner is using the exact same list like the arsenal. It's just ordered in a different way.
