### ISSUE TITLE
Logistic 1.0

### ISSUE THREAD

**Issue by Dorbedo** [Brig13Team/Operation_Kerberos#60]
- [x] paradrop add keybind
- [x] stack the goods
- [x] make a progressbar where the unit can't do something during the action (or use the one from ace)
- [x] unloading should not be possible if the unload area is blocked
- [x] disable seats
- [x] remove seats not placed on the cargo ramp from config
- [x] setWeight if you change the inventory of a container (XEH)

**Comment by Dorbedo** [comment]
Display left cargo space
no space left is shown

**Comment by Dorbedo** [comment]
Cargos are clipping
load 1 big -> load 1 tiny (ammocrate) -> load 1 big

**Comment by Dorbedo** [comment]
unloading multiple cargos at the same time:
some cargos can disappear

**Comment by iJesuz** [comment]
disable seats seams to work uncorrectly in arma 3 vanilla hemtt

**Comment by Dorbedo** [comment]
Maybe because of:


Lock all cargo positions of a vehicle or lock by index. This command must be executed where vehicle islocal.

**Comment by Dorbedo** [comment]
towing moved to #125
