### ISSUE TITLE
[Mainmissions] New Missions

### ISSUE THREAD

**Issue by iJesuz** [Brig13Team/Operation_Kerberos#68]
- [ ] rescue NATO forces which defend their position against mutiple attack waves
- [x] destroy drone commando
- [ ] search enemy specops
    Triangulate with satelites
- [ ] secure Outpost and provide medical treatment
- [ ] build a radar Station
- [ ] infiltrate Area
- [ ] disable/reactivate powerplant (Idea by EL Panda)
- [ ] clear road from roadblock and trash
- [ ] repair convoi
- [ ] rescure traitor
- [ ] defuse bomb
- [ ] undercover
- [ ] move back to base (small group beamed somewhere)
- [x] upload Virus
- [ ] meet contace persons

**Comment by Dorbedo** [comment]
integrated into #270
