### ISSUE TITLE
settings menu

### ISSUE THREAD

**Issue by Dorbedo** [Brig13Team/Operation_Kerberos#80]
new option menu for kerberos visible if you press ESC

**Comment by Dorbedo** [comment]
in combination with #62

**Comment by meat147** [comment]
why not use ace self interaction menu for stuff like this ? It has plenty of space left. Or do you want to keep the mission as independ as possible?

**Comment by Dorbedo** [comment]
The idea behind this was to put some not gameplay related stuff in this menue and some small admin tools.

We are already using the ACE-Interact Menue for the interactions with objects. (e.g. logistics, missionsobjects) or with yourself. But they are all gameplay related.

**Comment by meat147** [comment]
ok.

I would atleast put the vote yes/no stuff in the self interaction just because you can keep focus on gameplay.

**Comment by Dorbedo** [comment]
could be done with CBA_settings ?

**Comment by Dorbedo** [comment]
No own settings planned -> usage of CBA
