### ISSUE TITLE
Stationary (bunkered) tanks don't shoot

### ISSUE THREAD

**Issue by fratzi** [Brig13Team/Operation_Kerberos#87]
Stationary (bunkered) tanks don't shoot - currently they are no threat

**Comment by fratzi** [comment]
Same for artillery - they never shoot

**Comment by Dorbedo** [comment]
This is on intent. The artillery is controlled by the hq and will shoot on groups of units(players).

**Comment by Dorbedo** [comment]
changed in 0.17
