### ISSUE TITLE
Whitelist 

### ISSUE THREAD

**Issue by phumberdroz** [Brig13Team/Operation_Kerberos#92]
Hey,

i would add an whitelist for following roles.

Pilots, Command and Control Team

Also I would like to develop a Web Panel to administrate these Whitelists this would happen in a different repository.

**Comment by iJesuz** [comment]
Do you want to use a database based whitelist or a userconfig based whitelist like now?
Which kinds of c&c teams do you want to whitelist and is this really neccessary?

**Comment by meat147** [comment]
A database based Whitelist using arma2net to connect to the database from arma.

Well it is not if you do not feel like it. But if i call a JTAC and want it to be person that actually knows what his job is.

Application can be on different ways for example just a forum that he read the rules and terms or a training.

It is just to filter out new comers from joining these slots.

**Comment by Dorbedo** [comment]
I wouldn't whitelist a JTAC Unit -> every player can be a JTAC just using a Vector, a backpack-radio and a map. (and of course Skill ;) )

**Comment by iJesuz** [comment]
arma2net ist .NET based. Does the linux version of Mono support it?

**Comment by meat147** [comment]
Is the gameserver running on a linux machine ?

**Comment by iJesuz** [comment]
Yes, on Debian.

**Comment by Dorbedo** [comment]
whitelist changed into the usage of a database
